title: Gabe Poissant
description: Data Science Portfolio
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Hooks up header menu to "header_nav" menu
header:
  nav: "main"

# Enable sidebar, hooks up to 'side_nav' menu
sidebar:
  nav: "side_nav"

# Page default properties
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Load Google Fonts - Inter
google_fonts:
  - family: Inter:wght@400;500;600;700;800

# Enable author profile
author_profile: true

# Define sidebar author profile 
author:
  #name   : "Gabe Poissant"
  avatar : "/assets/images/profile_800.jpg"
  bio    : "Master’s in Data Science • Analytics • Finance"

  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:gabrielpoissant@gmail.com"

    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/gabepoissant"

    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/gabriel-poissant"

# Remove RSS from footer
atom_feed:
  hide: true

# Remove Credit from footer (sorry)
footer:
  links: []
  
powered_by: false

