title: Gabe Poissant
description: Data Science Portfolio
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

sidebar:
  nav: "main"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

custom_css:
  - /assets/css/custom.css

author_profile: true

author:
  name   : "Gabe Poissant"
  avatar : "/assets/images/profile_800.jpg"
  bio    : "Master’s in Data Science • Analytics • Finance"

  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:gabrielpoissant@gmail.com"

    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/gabepoissant"

    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "www.linkedin.com/in/gabriel-poissant"
