title: Gabe Poissant
description: Data Science Portfolio
remote_theme: mmistakes/minimal-mistakes

sidebar:
  nav: "main"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
